name: 'oscal-cli action'
description: 'Use oscal-cli to validate OSCAL content, convert OSCAL content, and perform processing of underlying Metaschema definitions'
inputs:
  args:
    description: 'Default arguments to run oscal-cli with'
    default: '--version'
    required: false
  debug:
    description: 'Enable debug output in action (set -x). Helpful for troubleshooting.'
    default: 'false'
    required: false
  oscalCliPackageUrl:
    description: 'The URL from which the oscal-cli package will be downloaded and installed.'
    default: 'https://repo1.maven.org/maven2/dev/metaschema/oscal/oscal-cli-enhanced/2.5.0/oscal-cli-enhanced-2.5.0-oscal-cli.tar.bz2'
    required: true
outputs:
  exit_code:
    description: "The exit code returned from oscal-cli"
    value: ${{ steps.oscal_cli.outputs.exit_code }}
runs:
  using: "composite"
  steps:
    - name: Install oscal-cli
      run: |
        curl -sL '${{ inputs.OSCALCLIPACKAGEURL }}' -o build.tar.bz2
        mkdir -p $HOME/.local/oscal-cli
        tar -C $HOME/.local/oscal-cli -xvjf build.tar.bz2
        echo "$HOME/.local/oscal-cli/bin" >> $GITHUB_PATH
      shell: bash
    - name: Run oscal-cli
      run: ${{ github.action_path }}/entrypoint.sh
      id: exec
      env:
        # https://github.com/actions/runner/issues/665
        INPUT_GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        INPUT_DEBUG: ${{ inputs.DEBUG }}
        INPUT_ARGS: ${{ inputs.ARGS }}
      shell: bash
branding:
  icon: "external-link"
  color: "purple"
